{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.0.0-rc02.aar",
          "url": "animation-1.0.0-rc02.aar",
          "size": 1249731,
          "sha512": "2f9bab0e5a953f107b100c8f0a2cfa3cb72ce9374bc6decca667327af0cb55a3a40ea34d8f051fb132f6ae6af93fd211abf0ecc0fc7e9a0bfb0aab89cf2fe2ee",
          "sha256": "a57b5a5b9eb2dd04c91530ce41a329857edb341b314103f81738ed03fa12cdb2",
          "sha1": "434149e62f0a718c8b4aaaed95fb658eae3d12f2",
          "md5": "0322eacdfc7c094ba3a19a560756ae32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.0.0-rc02.aar",
          "url": "animation-1.0.0-rc02.aar",
          "size": 1249731,
          "sha512": "2f9bab0e5a953f107b100c8f0a2cfa3cb72ce9374bc6decca667327af0cb55a3a40ea34d8f051fb132f6ae6af93fd211abf0ecc0fc7e9a0bfb0aab89cf2fe2ee",
          "sha256": "a57b5a5b9eb2dd04c91530ce41a329857edb341b314103f81738ed03fa12cdb2",
          "sha1": "434149e62f0a718c8b4aaaed95fb658eae3d12f2",
          "md5": "0322eacdfc7c094ba3a19a560756ae32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-1.0.0-rc02-sources.jar",
          "url": "animation-1.0.0-rc02-sources.jar",
          "size": 37035,
          "sha512": "c8dd5349bb81f8abe41ed31e2d96dae36f8d49a58bdb9b739d4ebbbb1d11d98a2f83b8477da44cc613f08eb453b91c5340cede8537435f9badcb459573799a85",
          "sha256": "3baf8e47e8c7600cf243706a93e20596bcacfbfcd1e4fed0c61ca453a627684c",
          "sha1": "e6e8324157b87ff500fa6e0de4a9272f5bdc37ba",
          "md5": "52baf39ee09ff3f6a5ae44d9495910fc"
        }
      ]
    }
  ]
}
