{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.0.0-rc02.aar",
          "url": "foundation-layout-1.0.0-rc02.aar",
          "size": 316451,
          "sha512": "6be2afd6757f6f79bc58c48dafc876073eee803f55d565f104812f551f64e80b74f721ac8bdcfc0a8ac0fb600cc58a0771ed44a6df4f191c4c1165e44f56fc2c",
          "sha256": "e5232635ce2899369d0518d047692488c0cf4c47d93dee772ec962ddd74d940b",
          "sha1": "143d587837340757d2447071eef9cb02ac4c264d",
          "md5": "f24dd6ed36479c4f6aab30f4cf2bc474"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.0.0-rc02.aar",
          "url": "foundation-layout-1.0.0-rc02.aar",
          "size": 316451,
          "sha512": "6be2afd6757f6f79bc58c48dafc876073eee803f55d565f104812f551f64e80b74f721ac8bdcfc0a8ac0fb600cc58a0771ed44a6df4f191c4c1165e44f56fc2c",
          "sha256": "e5232635ce2899369d0518d047692488c0cf4c47d93dee772ec962ddd74d940b",
          "sha1": "143d587837340757d2447071eef9cb02ac4c264d",
          "md5": "f24dd6ed36479c4f6aab30f4cf2bc474"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-layout-1.0.0-rc02-sources.jar",
          "url": "foundation-layout-1.0.0-rc02-sources.jar",
          "size": 40443,
          "sha512": "892cc3319657f82a57f7ad61e41c7c1ce337d99651ad0129f1d9e50d48daea7132e2ae85ac275140ac7c29e66fddb9a806486bdcf3dd34c2a5f3c8bea2f5b231",
          "sha256": "d19fc8f5df741e56f33e394695352c82ecd700aec8d3a597f492dda137b73d6d",
          "sha1": "1ae2a585cf8094a49d274c2d4aaf8ec6ac233270",
          "md5": "cc82913c9f6a1508537a7d671984d6b7"
        }
      ]
    }
  ]
}
