{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.0.0-rc02.aar",
          "url": "runtime-saveable-1.0.0-rc02.aar",
          "size": 1064630,
          "sha512": "e5cdf70041b1a85a474c900b33f777c79b056c612e23b29d28faeebc6456b5aa34febdc14c75f8a6322cc2fad6f187c5a784fb889b036e29e9bc61182f6579e8",
          "sha256": "1b4d5ad04208ead2a9656f72a6485612d23f1b4109d87b364f11f590ddd7b799",
          "sha1": "f0a65d3d6f39f7446f21bc380038f11011ed499d",
          "md5": "f7cfda49a7ee5efb66dcf53f3e29b9b5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.0.0-rc02.aar",
          "url": "runtime-saveable-1.0.0-rc02.aar",
          "size": 1064630,
          "sha512": "e5cdf70041b1a85a474c900b33f777c79b056c612e23b29d28faeebc6456b5aa34febdc14c75f8a6322cc2fad6f187c5a784fb889b036e29e9bc61182f6579e8",
          "sha256": "1b4d5ad04208ead2a9656f72a6485612d23f1b4109d87b364f11f590ddd7b799",
          "sha1": "f0a65d3d6f39f7446f21bc380038f11011ed499d",
          "md5": "f7cfda49a7ee5efb66dcf53f3e29b9b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-saveable-1.0.0-rc02-sources.jar",
          "url": "runtime-saveable-1.0.0-rc02-sources.jar",
          "size": 10689,
          "sha512": "519f8ecc62bd6c7dd22f2822806a5a062e7c8f2a342f43cbde73c79c89061711289f89f58d3d63ae7b48ae092238f4b743962f1d6bdcb19ab3f93d1a5b52a42f",
          "sha256": "4bdef461b704e497278c382096c6c6ec46199bce28172a1e2bac429068b84e7b",
          "sha1": "ec0084ff5e2fb11718572f078d23d23b61c1da4b",
          "md5": "9ebf7f4cbbcf803776f21cffc22d40c6"
        }
      ]
    }
  ]
}
