{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-1.0.0-rc02.aar",
          "url": "material-icons-extended-1.0.0-rc02.aar",
          "size": 26484546,
          "sha512": "6c0aa9ff683ff0fd9e93249817e9b558dbdaba06153f65c9222d7aa7673513f0938a4b6758941fc1b4af49f6f03e29c850ba4de6c4917a85bf0c4a5a6d562476",
          "sha256": "30a37b2a6b7f0212cbe1e1be4fbbfe92040db767075f65bd30e529117ad5f3d1",
          "sha1": "052b144f581fda583f4ae2443977fac0607c7778",
          "md5": "8d4d9c77d0f0ec789925048ca4362b51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-1.0.0-rc02.aar",
          "url": "material-icons-extended-1.0.0-rc02.aar",
          "size": 26484546,
          "sha512": "6c0aa9ff683ff0fd9e93249817e9b558dbdaba06153f65c9222d7aa7673513f0938a4b6758941fc1b4af49f6f03e29c850ba4de6c4917a85bf0c4a5a6d562476",
          "sha256": "30a37b2a6b7f0212cbe1e1be4fbbfe92040db767075f65bd30e529117ad5f3d1",
          "sha1": "052b144f581fda583f4ae2443977fac0607c7778",
          "md5": "8d4d9c77d0f0ec789925048ca4362b51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-extended-1.0.0-rc02-sources.jar",
          "url": "material-icons-extended-1.0.0-rc02-sources.jar",
          "size": 9082803,
          "sha512": "5b1f609ce30606fe04ed7ba9ec219a22f895bb903b9d6a38c2080ea0e859d5af7030c88069d553124015133bbb824eb0c35c6e8b78843415492cdd0287c0f995",
          "sha256": "06b64de7ec1e03d593ba87a49fa7a33544a6713beac427a11f38213e687ccf92",
          "sha1": "eeece86b3e05bbe9effb4811df1008d3d0e0cc8f",
          "md5": "d44dfebf75761fc87f7813f3bd8f955d"
        }
      ]
    }
  ]
}
