{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.0.0-rc02.aar",
          "url": "material-1.0.0-rc02.aar",
          "size": 2280310,
          "sha512": "fb7fda01e2ac4056f54f09112c93fe3d8d96a3d3e8e307daa2a224afe0ac9255a9954e0c0de6f55625817f6e98b1ee865703b2368112d1ff878a668daa307c51",
          "sha256": "7cf6432760548e1133283590710e053aeff25a0d034d2c6517cfd3bc465b78d1",
          "sha1": "2e9a90fb03e96b3697dc23276ad28e3312db5f41",
          "md5": "29e3d7779480e836c05a827177670855"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.0.0-rc02.aar",
          "url": "material-1.0.0-rc02.aar",
          "size": 2280310,
          "sha512": "fb7fda01e2ac4056f54f09112c93fe3d8d96a3d3e8e307daa2a224afe0ac9255a9954e0c0de6f55625817f6e98b1ee865703b2368112d1ff878a668daa307c51",
          "sha256": "7cf6432760548e1133283590710e053aeff25a0d034d2c6517cfd3bc465b78d1",
          "sha1": "2e9a90fb03e96b3697dc23276ad28e3312db5f41",
          "md5": "29e3d7779480e836c05a827177670855"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-1.0.0-rc02-sources.jar",
          "url": "material-1.0.0-rc02-sources.jar",
          "size": 166160,
          "sha512": "b177cb0d18e47d282d57c76052461d9eb6dd82c441b3c063fa7cd67d418d34b1e1e2e264c5885d6cabc4225028af7ca3b44a7b36b98622a5c04ea8a9948650b8",
          "sha256": "9d86de2259d6895a5cdb35294515b8c17ff2438aa2b69ce90ad0e4f6d58d0a54",
          "sha1": "b1fd7de2045e8ac5bcc5c0e05aaf9c8748c482e5",
          "md5": "c671a7a5c20f9ab6a7d87e8b308bebc9"
        }
      ]
    }
  ]
}
