{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.0.0-rc02.aar",
          "url": "material-icons-core-1.0.0-rc02.aar",
          "size": 686204,
          "sha512": "62a94207ccf06b22219cb196780ce8254049eddc44e5895f719c64f783c240f7b5712fb2156247c650fb25f657bbce6cc0977a1380a9db52e128ed94cb5717e0",
          "sha256": "f57b09bd82d8b44964376a96b3b53fffc6ffd9f8cf17eb86fb56e1c94ab3f590",
          "sha1": "efa55d717b49cfde146ab9aa7c9e150468bfe1d1",
          "md5": "0e0fa4e09049df1146bfbccea40b8c3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.0.0-rc02.aar",
          "url": "material-icons-core-1.0.0-rc02.aar",
          "size": 686204,
          "sha512": "62a94207ccf06b22219cb196780ce8254049eddc44e5895f719c64f783c240f7b5712fb2156247c650fb25f657bbce6cc0977a1380a9db52e128ed94cb5717e0",
          "sha256": "f57b09bd82d8b44964376a96b3b53fffc6ffd9f8cf17eb86fb56e1c94ab3f590",
          "sha1": "efa55d717b49cfde146ab9aa7c9e150468bfe1d1",
          "md5": "0e0fa4e09049df1146bfbccea40b8c3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-core-1.0.0-rc02-sources.jar",
          "url": "material-icons-core-1.0.0-rc02-sources.jar",
          "size": 240119,
          "sha512": "03bcd78849cb7a91014c675e4c0f9717912ed79ec759d214486a519f9f469b80bb32d507b100b9bc7458a6f20b6e749915a35bd50f1d4162f911642b67d5af2d",
          "sha256": "ec3e98c276fc21507b93c47e9290c28b538c77896cf0483bc2f78a5dc437ab67",
          "sha1": "f6ebb4e631e995de2b75617bed6175b0fe306294",
          "md5": "7a263fd8d6a465089336845f3de2e06b"
        }
      ]
    }
  ]
}
