{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-geometry",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.0.0-rc02.aar",
          "url": "ui-geometry-1.0.0-rc02.aar",
          "size": 37325,
          "sha512": "d45e4079407fdf321881d1aea0b8b73dd9d25449b064cd5c4a1a456a6be8033893dae4e4c14dfe730cf0002e95739dbb11cc594fd86a743492efdf6c0f8ebc94",
          "sha256": "ceddeb7493613015f83d9ca25242a9f1226a7da8bf84aadf7d901ae92ce714c6",
          "sha1": "81a9f5d8e61c5bce25b579d26e1717d1a2e4231c",
          "md5": "ba5eb3fdec8dc68c3ac9f1609c2ecba8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-1.0.0-rc02.aar",
          "url": "ui-geometry-1.0.0-rc02.aar",
          "size": 37325,
          "sha512": "d45e4079407fdf321881d1aea0b8b73dd9d25449b064cd5c4a1a456a6be8033893dae4e4c14dfe730cf0002e95739dbb11cc594fd86a743492efdf6c0f8ebc94",
          "sha256": "ceddeb7493613015f83d9ca25242a9f1226a7da8bf84aadf7d901ae92ce714c6",
          "sha1": "81a9f5d8e61c5bce25b579d26e1717d1a2e4231c",
          "md5": "ba5eb3fdec8dc68c3ac9f1609c2ecba8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-geometry-1.0.0-rc02-sources.jar",
          "url": "ui-geometry-1.0.0-rc02-sources.jar",
          "size": 17854,
          "sha512": "0eddfd791e910b05fcdc80ee048090628ad571bd83d58dd77e10d3e32a1a17e52f085e924b61c43f498578505ed03cec5d68099c45590918c85ad4b58d06f9c8",
          "sha256": "296a33c82f908a43b450389274d203465d2d14f6cab364e9c390411924cde988",
          "sha1": "be1f2ac9907309bae983a9ff69646a811493ebbf",
          "md5": "c505070ebf86fbbed3cf001c9ee9b99b"
        }
      ]
    }
  ]
}
