{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.0.0-rc02.aar",
          "url": "ui-tooling-preview-1.0.0-rc02.aar",
          "size": 11183,
          "sha512": "33b9b268512ef8d424276e5a17a5e380d9b131b724bc8cb5323fa8611567da1d7db6011cfece33d1f156fd778f153d3256dd64ba5ae86f76f9f4fde1695ad6f3",
          "sha256": "8954b3f2736642adbe37aae2caaa6f6f5fd6f39460f14de9b3f62fb8d414ec8d",
          "sha1": "88a40fa233192fd813c4702718d41e37d5c22561",
          "md5": "0bdda462536d8030801c07676bfefe79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.0.0-rc02.aar",
          "url": "ui-tooling-preview-1.0.0-rc02.aar",
          "size": 11183,
          "sha512": "33b9b268512ef8d424276e5a17a5e380d9b131b724bc8cb5323fa8611567da1d7db6011cfece33d1f156fd778f153d3256dd64ba5ae86f76f9f4fde1695ad6f3",
          "sha256": "8954b3f2736642adbe37aae2caaa6f6f5fd6f39460f14de9b3f62fb8d414ec8d",
          "sha1": "88a40fa233192fd813c4702718d41e37d5c22561",
          "md5": "0bdda462536d8030801c07676bfefe79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-preview-1.0.0-rc02-sources.jar",
          "url": "ui-tooling-preview-1.0.0-rc02-sources.jar",
          "size": 7885,
          "sha512": "bcd81d5b29b6bb97f9aec76ed6c4679a7e0855f1784ec636ddc685b4af63cb1ee14fdd52082fd699c61f8d48d6ec3c7005e810805284960d19f57015ea4d617a",
          "sha256": "c33f94f7d8e56826e2183a37ddeb640513e7be77d05b50bd3ef35382a926167e",
          "sha1": "90bbc79411d268373f8af19c38292749d4b2b15b",
          "md5": "2f79011292ae7c0c0de042f4353a48d9"
        }
      ]
    }
  ]
}
