{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.0.0-rc02.aar",
          "url": "ui-text-1.0.0-rc02.aar",
          "size": 458343,
          "sha512": "531b0ea2c52934031d00432782b0b8b5599036b5412a84e88a34cb81340985a952802f5dbba24f0e3e7d372a1583f54a180f4a50de791f4ca4895f64b44f09ad",
          "sha256": "f5dc2603cb39ab21371ece39d3333f1f0b4c32857e677c80f7bb7868daeb40c3",
          "sha1": "75d74c332f9221d99bfcf8f4bb39ecc261093e76",
          "md5": "936b09d0f6bbcace498516103d3d06b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.0.0-rc02.aar",
          "url": "ui-text-1.0.0-rc02.aar",
          "size": 458343,
          "sha512": "531b0ea2c52934031d00432782b0b8b5599036b5412a84e88a34cb81340985a952802f5dbba24f0e3e7d372a1583f54a180f4a50de791f4ca4895f64b44f09ad",
          "sha256": "f5dc2603cb39ab21371ece39d3333f1f0b4c32857e677c80f7bb7868daeb40c3",
          "sha1": "75d74c332f9221d99bfcf8f4bb39ecc261093e76",
          "md5": "936b09d0f6bbcace498516103d3d06b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-1.0.0-rc02-sources.jar",
          "url": "ui-text-1.0.0-rc02-sources.jar",
          "size": 172782,
          "sha512": "439c3de871dbf85920b37423112802f5cfaeab3fc48c900b66b02938549d02485a47f983acb27bb2a2500250b1e8c4fc19ac6c0d306c11f202544a5d960e0c7b",
          "sha256": "2a79c0efde7fa47a05030197ee438a792528d652bcebb863f90dd0a001b42e48",
          "sha1": "4536a690eae671aebd209959855372e537aee7d5",
          "md5": "e0b233deda01d1f7f83f5155a2769d4b"
        }
      ]
    }
  ]
}
