{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava2",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-1.0.0-rc02.aar",
          "url": "runtime-rxjava2-1.0.0-rc02.aar",
          "size": 23714,
          "sha512": "2cdc6a56b7292c9cc75b83f81cca5c01928f0014490def39169fb9cbbc7dc340554aafcc3353c16fc1b3ce1e47aaaefa9bbf520fa626993493d06482d39e45e7",
          "sha256": "4b23ae72a16fdf6b7466c038b7394cd0385108297cf251a4b2211315fbf9efda",
          "sha1": "b17d2bb92025096e661ffb7518801e757352a276",
          "md5": "1abcb20446a49d75be8d3e4c71d7f120"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-1.0.0-rc02.aar",
          "url": "runtime-rxjava2-1.0.0-rc02.aar",
          "size": 23714,
          "sha512": "2cdc6a56b7292c9cc75b83f81cca5c01928f0014490def39169fb9cbbc7dc340554aafcc3353c16fc1b3ce1e47aaaefa9bbf520fa626993493d06482d39e45e7",
          "sha256": "4b23ae72a16fdf6b7466c038b7394cd0385108297cf251a4b2211315fbf9efda",
          "sha1": "b17d2bb92025096e661ffb7518801e757352a276",
          "md5": "1abcb20446a49d75be8d3e4c71d7f120"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-rxjava2-1.0.0-rc02-sources.jar",
          "url": "runtime-rxjava2-1.0.0-rc02-sources.jar",
          "size": 2227,
          "sha512": "4ccb09788677591ff07ba2857e2a2c680c1f438e549f8c15fb6cde63f0efe07876269ed4a1036aaa4385c7f0fa3c7f97df3cbb27862f6bd9bf6df625481cf14a",
          "sha256": "342468c598af52c3071cab1f42a632ed6a6865d7faf66c3fd6d346ef2223628d",
          "sha1": "6b1b6ccf1fab2c2026994d1dc69a2b9e9db8ddbe",
          "md5": "8ab41ef7a0d228255e99d085ba61f207"
        }
      ]
    }
  ]
}
