{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.0.0-rc02.aar",
          "url": "runtime-livedata-1.0.0-rc02.aar",
          "size": 7084,
          "sha512": "3e26529640ebddbc365b8ef2af24db306224001533c1b19d7bf62ee069b41ce5f66f2b6c1d08c23970ba79e7d9d30f222dc090d41c9a29a8cc293e02791fa576",
          "sha256": "a426fcac2aec3ccfac5553deb658403a8cbc4ec43762124fae7c3b256dfe79b6",
          "sha1": "3419b15edff73bdd0379b201cfbd0d598ef2f95d",
          "md5": "d97b8fcc52a0a82f4ce853da17ee3416"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.0.0-rc02.aar",
          "url": "runtime-livedata-1.0.0-rc02.aar",
          "size": 7084,
          "sha512": "3e26529640ebddbc365b8ef2af24db306224001533c1b19d7bf62ee069b41ce5f66f2b6c1d08c23970ba79e7d9d30f222dc090d41c9a29a8cc293e02791fa576",
          "sha256": "a426fcac2aec3ccfac5553deb658403a8cbc4ec43762124fae7c3b256dfe79b6",
          "sha1": "3419b15edff73bdd0379b201cfbd0d598ef2f95d",
          "md5": "d97b8fcc52a0a82f4ce853da17ee3416"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-livedata-1.0.0-rc02-sources.jar",
          "url": "runtime-livedata-1.0.0-rc02-sources.jar",
          "size": 1824,
          "sha512": "12fdf7b2e70e16d3bcb59966d8e05b36b9698923cb467e376ee542aa1c98f87996f1b204a688dd2f783701a67055260ab797b6bc70e046df095bb535c7d505a2",
          "sha256": "2940823fd4f14afcab6a5aa9ad79f2a353f78c1312f9251fdd7c017ad171cff9",
          "sha1": "a36eb1d628eb1d76e540e9357a1330ade67e328c",
          "md5": "9900ddee4f1294723a75e9a0837241e3"
        }
      ]
    }
  ]
}
