{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling-data",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-data-1.0.0-rc02.aar",
          "url": "ui-tooling-data-1.0.0-rc02.aar",
          "size": 29158,
          "sha512": "96542dcf15dcd843d82bf90407f06013538169917a8e48563b4810067e4e0a8bd461a21f0e29746ac09d1165f8c1832c4f72454c700594dca57c40297ca0b108",
          "sha256": "dc31339f1bc42efe53636cf810a817b5c9c53d3c6d59417ba03706a23f5d760e",
          "sha1": "01fbf50e973297787813a2d0ef1396cb2533f5eb",
          "md5": "356b9c9a234b231705a233c94d6ac800"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-data-1.0.0-rc02.aar",
          "url": "ui-tooling-data-1.0.0-rc02.aar",
          "size": 29158,
          "sha512": "96542dcf15dcd843d82bf90407f06013538169917a8e48563b4810067e4e0a8bd461a21f0e29746ac09d1165f8c1832c4f72454c700594dca57c40297ca0b108",
          "sha256": "dc31339f1bc42efe53636cf810a817b5c9c53d3c6d59417ba03706a23f5d760e",
          "sha1": "01fbf50e973297787813a2d0ef1396cb2533f5eb",
          "md5": "356b9c9a234b231705a233c94d6ac800"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-data-1.0.0-rc02-sources.jar",
          "url": "ui-tooling-data-1.0.0-rc02-sources.jar",
          "size": 7034,
          "sha512": "e33bc8932142dc851680de6c9d5589399a111c9ef13c89da8912988d5e695920d7d666ef6d341104d738d439b1751e28a237833d42600d83a08a752d1244b402",
          "sha256": "270d9b613a3d794fef2d2611ef653b106271ca2827869ebdce45e60cad6dc30e",
          "sha1": "d662e515728e07a0c647114ec8aa295b0b7600c5",
          "md5": "a4e9e16f983061f969a5a13d3f2ed692"
        }
      ]
    }
  ]
}
