{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-1.0.0-rc02.aar",
          "url": "material-ripple-1.0.0-rc02.aar",
          "size": 73394,
          "sha512": "3cef6c4ca545b1c6646c007c63404553eb6e670ec220cbd50782289fdad42fa4e05730bddb6607c198d637e91c0cddd4febb31d7f3f26645a552fff44bb7f361",
          "sha256": "dc36b9ac9df6f595adc9e5d01abe91c6f17c62222db302d3ffd0666c879b33f4",
          "sha1": "03a52471b91d4bb078d5fe9a3c2d9104b5038ad6",
          "md5": "8c66c70090ea149a60d1eea833e56d7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-1.0.0-rc02.aar",
          "url": "material-ripple-1.0.0-rc02.aar",
          "size": 73394,
          "sha512": "3cef6c4ca545b1c6646c007c63404553eb6e670ec220cbd50782289fdad42fa4e05730bddb6607c198d637e91c0cddd4febb31d7f3f26645a552fff44bb7f361",
          "sha256": "dc36b9ac9df6f595adc9e5d01abe91c6f17c62222db302d3ffd0666c879b33f4",
          "sha1": "03a52471b91d4bb078d5fe9a3c2d9104b5038ad6",
          "md5": "8c66c70090ea149a60d1eea833e56d7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-ripple-1.0.0-rc02-sources.jar",
          "url": "material-ripple-1.0.0-rc02-sources.jar",
          "size": 21613,
          "sha512": "308ef2200c1f6ed8dce2e36c358a86fed32e72ecd176a5d78ba6d26d63b6971396a6c0308ecb06f4a411e1ee827285be6dbcd031329668593ef11d2754ead1c6",
          "sha256": "74efa065f16234f7b7bfe11522835126d9130ecc070126cdb5066f635c24c5f8",
          "sha1": "f16836cbe2ea18afd48a92a6a2c6e34f58d61a2e",
          "md5": "7ad01ac8b80527f0e5afd34034dda55e"
        }
      ]
    }
  ]
}
