{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-rc02.aar",
          "url": "ui-unit-1.0.0-rc02.aar",
          "size": 58469,
          "sha512": "861b8d1ca0ca802f5e539bf8b9dbd59d97821aeabe3b36d6f57b56c4acb77107ddd926a94f6cc0a180abd25d1600abd81f9ad517cb3cd0898b0cc61efa623e81",
          "sha256": "3f00fd33c4b7fafb1de2a973be3cd6c8b48e1b727fce86adf17c2d0b444bd371",
          "sha1": "32b653aac981f9212f3a5278a6248509ab31e138",
          "md5": "1ea92b20e54f9b8e6f0c316575c27cf7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-rc02.aar",
          "url": "ui-unit-1.0.0-rc02.aar",
          "size": 58469,
          "sha512": "861b8d1ca0ca802f5e539bf8b9dbd59d97821aeabe3b36d6f57b56c4acb77107ddd926a94f6cc0a180abd25d1600abd81f9ad517cb3cd0898b0cc61efa623e81",
          "sha256": "3f00fd33c4b7fafb1de2a973be3cd6c8b48e1b727fce86adf17c2d0b444bd371",
          "sha1": "32b653aac981f9212f3a5278a6248509ab31e138",
          "md5": "1ea92b20e54f9b8e6f0c316575c27cf7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-1.0.0-rc02-sources.jar",
          "url": "ui-unit-1.0.0-rc02-sources.jar",
          "size": 22416,
          "sha512": "7c744e93c27b0df61a0b7b9f20905a87d3c0cc6ef416ac9cb925aed94d676ac0bd9535c1e6d172f3fd1c5bcbe6ad5e36f27b4c020a587e7b1ef754e431a77cfc",
          "sha256": "29cb4725727489de83af6bae8ae4caf0cdefa7a753249971d94803bfde5b3375",
          "sha1": "822426fd329ea50c34bf679854660862568c457d",
          "md5": "ae938d70449087115c8664deef1400ec"
        }
      ]
    }
  ]
}
