{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.0.0-rc02.aar",
          "url": "foundation-1.0.0-rc02.aar",
          "size": 1206166,
          "sha512": "e7bb18d90b3e00fe5c4b9c61d4006714e37dbeb351e4d723ddc2dafac0035b3334433c86576135d32978f6ce50d4cea3b522b117b5f9f558732e018e005fa607",
          "sha256": "e42990d755b5beb6753f31efde4bc419088ff1e058f6ac44d25d0d94c8b67f4f",
          "sha1": "862cc73752401e949a3ff59db612e4e90074f9d4",
          "md5": "549d26f0d5330425d5e9e734de50edfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.0.0-rc02.aar",
          "url": "foundation-1.0.0-rc02.aar",
          "size": 1206166,
          "sha512": "e7bb18d90b3e00fe5c4b9c61d4006714e37dbeb351e4d723ddc2dafac0035b3334433c86576135d32978f6ce50d4cea3b522b117b5f9f558732e018e005fa607",
          "sha256": "e42990d755b5beb6753f31efde4bc419088ff1e058f6ac44d25d0d94c8b67f4f",
          "sha1": "862cc73752401e949a3ff59db612e4e90074f9d4",
          "md5": "549d26f0d5330425d5e9e734de50edfb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-1.0.0-rc02-sources.jar",
          "url": "foundation-1.0.0-rc02-sources.jar",
          "size": 235511,
          "sha512": "c6eda78a912baf715ceb78fabf2f93c77ff9233efbdcea124f8feb3813ee4c7a428c13cbe1d2cf09c36910cca79d5cb0a654d471db212534a1acd6898e7d63eb",
          "sha256": "2684f571446acb01cb430718d8e64fba9a9927ab0f094f7a778e3b0eb57fc3d3",
          "sha1": "4193a37684eb9621715649ba0f8f84b842c77560",
          "md5": "271d8e89c82a2c63ef96eb71569c9f6a"
        }
      ]
    }
  ]
}
