{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-1.0.0-rc02.aar",
          "url": "ui-tooling-1.0.0-rc02.aar",
          "size": 85170,
          "sha512": "929f180fb0fd7267323201a1f274af31687d4d915f8245963392235cb7eafdebfd2426741d16b7eff7f9119367ec9d6ac95f6ca549c40162c6ac681e5ae823e2",
          "sha256": "56fe5c1562e645c647c2d8b4d583b4b0cf401825b00d675e04a6b1099d2ff13e",
          "sha1": "4e2b4d8b7c21922699e5adede71421ab3dee796c",
          "md5": "4bc696cc658687cf99a6b7a18c60fc13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-1.0.0-rc02.aar",
          "url": "ui-tooling-1.0.0-rc02.aar",
          "size": 85170,
          "sha512": "929f180fb0fd7267323201a1f274af31687d4d915f8245963392235cb7eafdebfd2426741d16b7eff7f9119367ec9d6ac95f6ca549c40162c6ac681e5ae823e2",
          "sha256": "56fe5c1562e645c647c2d8b4d583b4b0cf401825b00d675e04a6b1099d2ff13e",
          "sha1": "4e2b4d8b7c21922699e5adede71421ab3dee796c",
          "md5": "4bc696cc658687cf99a6b7a18c60fc13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-1.0.0-rc02-sources.jar",
          "url": "ui-tooling-1.0.0-rc02-sources.jar",
          "size": 20536,
          "sha512": "e6ec78695f9edfa7d15efed0eac283ebf986c5425acde6e4ac360081f81a0d4a200297dd278ced0ea9fd57ce505461ef16b2b8d7cc0cd6835b05c31a9ee17140",
          "sha256": "25010189606e47d18f9084f7da2d8912f84c6ab03728740e637a9c85ae9a254e",
          "sha1": "27b5820f12f696d18f82fa9b55abe1fbd25bcacd",
          "md5": "27001a47e45622d410529275d2fa9337"
        }
      ]
    }
  ]
}
