{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.profileinstaller",
    "module": "profileinstaller",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.0.0-rc02.aar",
          "url": "profileinstaller-1.0.0-rc02.aar",
          "size": 27580,
          "sha512": "e7173a3ecd4f3205dbb0fc2eb20b1b1a8f4a8f848d4a7cfcd795f1eb85264087514540ea43c9c12e5b1f2f7309acd3703ba7e85d69b701493046373fe47ebaa9",
          "sha256": "5c44147561f21c679099c0569858e193b64a19bd11701b19d0aa1789cd13fd0b",
          "sha1": "494cc2d3d2135b255e477046bcf05735eff669e4",
          "md5": "7d56588f96e55d34cbba5cef8e9e791d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.0.0-rc02.aar",
          "url": "profileinstaller-1.0.0-rc02.aar",
          "size": 27580,
          "sha512": "e7173a3ecd4f3205dbb0fc2eb20b1b1a8f4a8f848d4a7cfcd795f1eb85264087514540ea43c9c12e5b1f2f7309acd3703ba7e85d69b701493046373fe47ebaa9",
          "sha256": "5c44147561f21c679099c0569858e193b64a19bd11701b19d0aa1789cd13fd0b",
          "sha1": "494cc2d3d2135b255e477046bcf05735eff669e4",
          "md5": "7d56588f96e55d34cbba5cef8e9e791d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profileinstaller-1.0.0-rc02-sources.jar",
          "url": "profileinstaller-1.0.0-rc02-sources.jar",
          "size": 20658,
          "sha512": "4886ff991307402df11028ca0072695140b708b4643a7b00298c4b48e4d7df840f4670cf3a3a3c0d164e26b107630ae342f2ffcd8f61cb002ad1985663a60386",
          "sha256": "798207652a53ee69b34f75f03716441d3221edb121d7dd1032bd7ae1be74293b",
          "sha1": "8da06d1829dd71326bb0eb488d0e2b647d37809f",
          "md5": "eb9a21dffa7a5eebb4a6ce12df21f29f"
        }
      ]
    }
  ]
}
