{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.0.0-rc02.aar",
          "url": "ui-graphics-1.0.0-rc02.aar",
          "size": 1369055,
          "sha512": "1787982f140e4e5449e5565efa6fcffc3d1a674239e76ae6c82569186659b03030c6583b5c1711e41c953cedab30a465c6033074bb6bfce508f6c9c683c57ddc",
          "sha256": "d9b17d59bc71effe16818e4d6b88f35c6a09065085e620f8bfc8a5d53bdd735d",
          "sha1": "7e4e125717f7a5b6b8d89fd81d0fd2a9a8b823c1",
          "md5": "9c30441be49ae384ab8d8052986e3976"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.0.0-rc02.aar",
          "url": "ui-graphics-1.0.0-rc02.aar",
          "size": 1369055,
          "sha512": "1787982f140e4e5449e5565efa6fcffc3d1a674239e76ae6c82569186659b03030c6583b5c1711e41c953cedab30a465c6033074bb6bfce508f6c9c683c57ddc",
          "sha256": "d9b17d59bc71effe16818e4d6b88f35c6a09065085e620f8bfc8a5d53bdd735d",
          "sha1": "7e4e125717f7a5b6b8d89fd81d0fd2a9a8b823c1",
          "md5": "9c30441be49ae384ab8d8052986e3976"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-1.0.0-rc02-sources.jar",
          "url": "ui-graphics-1.0.0-rc02-sources.jar",
          "size": 152723,
          "sha512": "a12b1b8d7daae1d03fa1938f0ce681f398b26d3dc69dfb33d4725f4bf023b05f144137dbb1a87070a1306f1bd61aac466d90dfb4ed1a5755db92a2ba677684b5",
          "sha256": "1e1387f756868e14dd848c00dc0c9783b594c6a047eae13a08fd36f254748fad",
          "sha1": "99e2112f5a1a0c64eff13c5543ba1bf1a9a3c3a3",
          "md5": "6e22d60f52fcff97761038049b370d45"
        }
      ]
    }
  ]
}
