{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.0.0-rc02.aar",
          "url": "runtime-1.0.0-rc02.aar",
          "size": 1859206,
          "sha512": "23f30c32a4686458f29b68e89d960c562e16bfbff73f674e90bd4f09fa2520c69d65804a935d7530c99ba782ad32f187700c4c029e0d68450e5fb3e956754d0e",
          "sha256": "b36498f5bf6c502228727e32b60ff25797a5d369085395cfe623bcf83c992a75",
          "sha1": "f0fd56076e4e6805825cbeb3b874566bc633d101",
          "md5": "23c9850b6b6db0e1e56a7be3b87ff310"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.0.0-rc02.aar",
          "url": "runtime-1.0.0-rc02.aar",
          "size": 1859206,
          "sha512": "23f30c32a4686458f29b68e89d960c562e16bfbff73f674e90bd4f09fa2520c69d65804a935d7530c99ba782ad32f187700c4c029e0d68450e5fb3e956754d0e",
          "sha256": "b36498f5bf6c502228727e32b60ff25797a5d369085395cfe623bcf83c992a75",
          "sha1": "f0fd56076e4e6805825cbeb3b874566bc633d101",
          "md5": "23c9850b6b6db0e1e56a7be3b87ff310"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-1.0.0-rc02-sources.jar",
          "url": "runtime-1.0.0-rc02-sources.jar",
          "size": 254696,
          "sha512": "4a19ddd40ae5a46c83237b6a3a56cd2f7e53b783468211a797c5063c34edc2b492d24420416eccfa0b074bf25cbde66c72809b88b22e6acfe9d7ae6e2d1c355f",
          "sha256": "eb9601e7c5bf4ef1bb84c685216ee09ccf7fb377fc23a9f070f066ebe65be1ef",
          "sha1": "028faf010a9171f3493f48d7d9cb15bc978c357c",
          "md5": "49f8c57cff384db5b8f1f29ed977ca19"
        }
      ]
    }
  ]
}
