{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.0.0-rc02.aar",
          "url": "animation-core-1.0.0-rc02.aar",
          "size": 1288381,
          "sha512": "1da222b7b0c70a2dd53c64de3c594d456d2b1f632888ab76c202fe1b24271e9ef5dff07b3e9aa123a839ffef3b78a5a70e9c76452f3af5f1fe95c9ab9cd2546d",
          "sha256": "5f6a43fc017f8836e9426839f01afa2f22d1be9446dbd147298123d41dbcf4b4",
          "sha1": "60fb3972ee0658fd6a0e428770ca6e31694b9717",
          "md5": "776a31066a1c36b64e4a025c3e9abde8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.0.0-rc02.aar",
          "url": "animation-core-1.0.0-rc02.aar",
          "size": 1288381,
          "sha512": "1da222b7b0c70a2dd53c64de3c594d456d2b1f632888ab76c202fe1b24271e9ef5dff07b3e9aa123a839ffef3b78a5a70e9c76452f3af5f1fe95c9ab9cd2546d",
          "sha256": "5f6a43fc017f8836e9426839f01afa2f22d1be9446dbd147298123d41dbcf4b4",
          "sha1": "60fb3972ee0658fd6a0e428770ca6e31694b9717",
          "md5": "776a31066a1c36b64e4a025c3e9abde8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-1.0.0-rc02-sources.jar",
          "url": "animation-core-1.0.0-rc02-sources.jar",
          "size": 69581,
          "sha512": "63939bdc4a1818d34b299bbdc3cad39362e3072529e828e64740714fcb178815b0b6ba0d75b91e542e276598dce24f0667efd29680c8ed47d7babb1a3d1ae387",
          "sha256": "bf0748117142aa4525ccf8c74b83a6be0d98ca7c7c68e9919043f44a8a8757b4",
          "sha1": "c230b84f27ee79adf5e8d6115cdf6c3f89f5b7fd",
          "md5": "589f869157655564c0a63445369bf2fe"
        }
      ]
    }
  ]
}
