{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.3.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.3.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.3.0-rc02.aar",
          "url": "activity-compose-1.3.0-rc02.aar",
          "size": 27604,
          "sha512": "4df9a1eff091e358e04ab9efaf94d2636022d2f470e6a3152898795fbb571daa161d7bf7ff54ce57accf52492df9d201f52335c49321f7bfe2ce44f5ba13f16f",
          "sha256": "62cfbcf06a1b114a483309f5462cf1fe64385d936cccac74e3b4c96d4e10d5d2",
          "sha1": "1382dc2f66e8fc6f24c3e433e5f3c3f7a07d7e96",
          "md5": "26040dff6225827de8a57f5829e7bab0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.3.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.3.0-rc02.aar",
          "url": "activity-compose-1.3.0-rc02.aar",
          "size": 27604,
          "sha512": "4df9a1eff091e358e04ab9efaf94d2636022d2f470e6a3152898795fbb571daa161d7bf7ff54ce57accf52492df9d201f52335c49321f7bfe2ce44f5ba13f16f",
          "sha256": "62cfbcf06a1b114a483309f5462cf1fe64385d936cccac74e3b4c96d4e10d5d2",
          "sha1": "1382dc2f66e8fc6f24c3e433e5f3c3f7a07d7e96",
          "md5": "26040dff6225827de8a57f5829e7bab0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-compose-1.3.0-rc02-sources.jar",
          "url": "activity-compose-1.3.0-rc02-sources.jar",
          "size": 6677,
          "sha512": "7c2cfbe24b69b4fa424526eb6d5a420770fffcdcb7182e70d024a6ddb222f265c406ebc29caa7ae9a640669c3129a7eb99750c3169e6ac1ee86d6273531c4a0f",
          "sha256": "0c6dd49edddd2ffdc2c3352644b7510d18be6752425b79d1f21505a37ea59190",
          "sha1": "1c7254d3de5b5c2734601aa4b3d52509984b3f75",
          "md5": "33584ea6366f0b3d0100f8ab5bfb49dd"
        }
      ]
    }
  ]
}
