{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-util-1.0.0-rc02.aar",
          "url": "ui-util-1.0.0-rc02.aar",
          "size": 7871,
          "sha512": "06441c38d928cb352a40bf433292fa9c6e277298e687069f6ae86da12390ba76dde5c95c5fe7fa772d0f5fd3cbe245c985c1f2173dcc6f1cf122512e48f19e98",
          "sha256": "deaba240830ce59f34b6d29bd6001652f8786090a7b6574847b61487774accba",
          "sha1": "5af956dbc7f88f5e0f558658d13456224edbb554",
          "md5": "93cf90a08625181b0be35dca9246ca15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-1.0.0-rc02.aar",
          "url": "ui-util-1.0.0-rc02.aar",
          "size": 7871,
          "sha512": "06441c38d928cb352a40bf433292fa9c6e277298e687069f6ae86da12390ba76dde5c95c5fe7fa772d0f5fd3cbe245c985c1f2173dcc6f1cf122512e48f19e98",
          "sha256": "deaba240830ce59f34b6d29bd6001652f8786090a7b6574847b61487774accba",
          "sha1": "5af956dbc7f88f5e0f558658d13456224edbb554",
          "md5": "93cf90a08625181b0be35dca9246ca15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-util-1.0.0-rc02-sources.jar",
          "url": "ui-util-1.0.0-rc02-sources.jar",
          "size": 4574,
          "sha512": "0d0d4178392cad87a78875b6d4cfd2aa27860ddfc0115c3a7f13003e7834503f32697f885b0c1b4aad56d409e258480b0e891e0711fe019028bc96866f33be6e",
          "sha256": "c72c6cf6834497e42f09c61f4e3e17a8bdc1b2add6dce25b546fbe6176322b34",
          "sha1": "69426082fe7d7ebbd25c1f8f755d2ee2b65b46da",
          "md5": "26e3ab71e8414dd37d17637ab86d2d3d"
        }
      ]
    }
  ]
}
